name: skydroid
description: A decentralized domain-based App Store for Android.

publish_to: "none"

version: 0.5.4+54

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Internationalization support.
  flutter_localizations:
    sdk: flutter
  http: ^0.12.2
  path_provider: ^1.6.11
  permission_handler: ^5.0.1+1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  yaml: ^2.2.1
  crypto: ^2.1.4
  cached_network_image: ^2.2.0+1
  flutter_html: ^1.2.0
  markdown: ^2.1.5
  flutter_animation_progress_bar: ^1.0.0
  filesize: ^1.0.4
  device_apps: ^1.2.0
  url_launcher: ^5.5.0
  share: ^0.6.4+3
  material_design_icons_flutter: ^4.0.5345
  preferences: ^5.2.0
  json_annotation: ^3.0.1
  time_ago_provider: ^2.0.5
  flutter_device_locale: ^0.4.0
  package_info: ^0.4.1
  uni_links: ^0.4.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  convert: ^2.1.1
  system_info: ^0.1.3
  device_info: ^1.0.0
  pool: ^1.4.0
  path: ^1.7.0
  logger: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1
  hive_generator: ^0.8.2
  build_runner: ^1.11.1
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/adaptive_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/fallback.png
    - assets/icon/icon.png
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
